### ISSUE TITLE
ERROR: No matching distribution found for drake==1.30.0

### ISSUE THREAD

**Issue by zichunxx** [sea-bass/pyroboplan#73]
Hi! Thanks for your nice work!

I tried to install `pyroboplan` from source in conda env and met the following error: 

```
ERROR: Could not find a version that satisfies the requirement drake==1.30.0 (from pyroboplan) (from versions: 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.26.0)
ERROR: No matching distribution found for drake==1.30.0
```

Is the lower version of `drake` available for the current version of `pyroboplan`?

**Comment by sea-bass** [comment]
Based on those available versions, you seem to be on Python 3.8, which I have not tested on. I've been doing Python 3.10 and 3.12.

So you could try relax the requirements to use Drake 1.26.0 (the latest available on that version), but I can't guarantee that the rest of the package will work. Worth a try, though?

**Comment by sea-bass** [comment]
It looks to me like there is a Pinocchio conflict between a ROS 2 Foxy install (hence Python 3.8) and whatever was installed by this. Basically, a ROS 2 version of this: https://github.com/stack-of-tasks/pinocchio/issues/1229

Could you try do a `sudo apt-get remove ros-foxy-pinocchio` and try again, by any chance?

**Comment by sea-bass** [comment]
Here's another issue that might be helpful: https://github.com/stack-of-tasks/pinocchio/issues/1960
