### ISSUE TITLE
Documentation clarification: `RRT-Connect` vs `Bidirectional-RRT`

### ISSUE THREAD

**Issue by adlarkin** [sea-bass/pyroboplan#74]
Hey Sebastian,

Thanks for all of the work you've done here. This has been a great resource for me! I was reading through the `rrt` code, and wonder if we can make the docs for the `rrt_connect` and `bidirectional_rrt` args a little clearer: https://github.com/sea-bass/pyroboplan/blob/fd0d28915b9285c87f50694ae285d321209801b5/src/pyroboplan/planning/rrt.py#L50-L55

Looking at the [RRT-connect paper](https://www.cs.cmu.edu/afs/cs/academic/class/15494-s14/readings/kuffner_icra2000.pdf), it seems like the only difference between `RRT-connect` and `bidirectional-RRT` is that `RRT-connect` uses a greedy heuristic for expanding the other tree towards the newly extended configuration (as the paper would say, `connect` instead of `extend`), while `bidirectional-RRT` uses `extend` for both trees (i.e., no greedy expansion via `connect`). This is based on what I read [here](https://metr4202.uqcloud.net/cache/LaValle%20Kuffner.Randomized%20Kinodynamic%20Planning.IJRR.2001.pdf) (see section `4.2`).

If my understanding is correct, I can make a PR to clarify these params a little more. I can also add the `bidirectional-RRT` paper I linked above to your [resources](https://github.com/sea-bass/pyroboplan/blob/fd0d28915b9285c87f50694ae285d321209801b5/src/pyroboplan/planning/rrt.py#L92) if you think that's a good addition (let me know if there's a better link to use for that paper, I was just trying to find the PDF via google search)

**Comment by sea-bass** [comment]
This is all a good addition and I would welcome the changes!

@eholum would concur, I'm sure, since we've had similar discussions about the difference (or lack thereof) between these two flavors of RRT.

**Comment by eholum** [comment]
Ah, I think those param descriptions are swapped? Did we make peace with the idea that "connect" refers to the heuristic and "bidirectional" means two trees? I think so...

https://github.com/sea-bass/pyroboplan/blob/main/src/pyroboplan/planning/rrt.py#L302

**Comment by sea-bass** [comment]
Yes @ that distinction, and wow. The docstrings are indeed swapped. Haha.

**Comment by adlarkin** [comment]
> Did we make peace with the idea that "connect" refers to the heuristic and "bidirectional" means two trees? I think so...

I see; okay, then I think the docstrings just need to be re-swapped back to their original locations. I also think that it would be better to clarify that for RRT connect, we are not extending "towards a random node", but rather continually extending the most recently sampled node. PR is up if either of you want to take a look: #75
